### ISSUE TITLE
тлф: форма обрезается и скроллится, хотя еще есть место на екране

### ISSUE THREAD

**Issue by VladyslavKovalchuk** [MalahVitalij/rocket-impuls25#13]
http://prntscr.com/l4259m
http://prntscr.com/l425cz

**Comment by VladyslavKovalchuk** [comment]
конкретно в хроме

**Comment by Sashamailrias** [comment]
Поднять форму, так как нижняя панелька перекрывает кнопку http://prntscr.com/l70vnp
