### ISSUE TITLE
Поменять цвет подменю

### ISSUE THREAD

**Issue by Sashamailrias** [MalahVitalij/rocket-impuls25#23]
http://prntscr.com/l706ca 
На моб, в подменю (2) нужно поменять черный цвет на сероватый как у оборудования (1)

**Comment by VladyslavKovalchuk** [comment]
в меню на других страницах кроме главной тоже исправить http://prntscr.com/l74osw

**Comment by VladyslavKovalchuk** [comment]
на стр контакты в подменю нет подменю для оборудования http://prntscr.com/l7ya04
